[project]
name = "hellolm-v2"
version = "0.1.0"
description = "play a simple language model"
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "pyarrow>=19.0.1",
    "sortedcontainers>=2.4.0",
    "tiktoken>=0.9.0",
    "torch>=2.6.0",
]
